dist: xenial

language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - 3.7

install:
  - pip install --upgrade pip
  - pip install -U nose numpy matplotlib pandas coverage
  - pip install -e .

script:
  - nosetests --with-coverage --cover-package=pyblock --cover-min-percentage=85 pyblock
